const regulations = {
  "United Kingdom": `<h2>United Kingdom</h2><p><a href="https://www.caa.co.uk/drones/" target="_blank">https://www.caa.co.uk/drones/</a></p>`,
  "Austria": `<h2>Austria</h2><p><a href="https://www.austrocontrol.at" target="_blank">https://www.austrocontrol.at</a></p>`,
  "Belgium": `<h2>Belgium</h2><p><a href="https://www.mobilit.belgium.be/fr/transport_aerien" target="_blank">https://www.mobilit.belgium.be/fr/transport_aerien</a></p>`,
  "Bulgaria": `<h2>Bulgaria</h2><p><a href="http://www.caa.bg/en" target="_blank">http://www.caa.bg/en</a></p>`,
  "Croatia": `<h2>Croatia</h2><p><a href="http://www.ccaa.hr/en" target="_blank">http://www.ccaa.hr/en</a></p>`,
  "Cyprus": `<h2>Cyprus</h2><p><a href="http://www.mcw.gov.cy/mcw/dca/dca.nsf" target="_blank">http://www.mcw.gov.cy/mcw/dca/dca.nsf</a></p>`,
  "Czech Republic": `<h2>Czech Republic</h2><p><a href="http://www.caa.cz/en" target="_blank">http://www.caa.cz/en</a></p>`,
  "Denmark": `<h2>Denmark</h2><p><a href="https://www.trafikstyrelsen.dk/en/civil-aviation.aspx" target="_blank">https://www.trafikstyrelsen.dk/en/civil-aviation.aspx</a></p>`,
  "Estonia": `<h2>Estonia</h2><p><a href="http://www.ecaa.ee/en" target="_blank">http://www.ecaa.ee/en</a></p>`,
  "Finland": `<h2>Finland</h2><p><a href="https://www.traficom.fi/en/transport/aviation" target="_blank">https://www.traficom.fi/en/transport/aviation</a></p>`,
  "France": `<h2>France</h2><p><a href="https://www.ecologie.gouv.fr/politiques/aviation-civile" target="_blank">https://www.ecologie.gouv.fr/politiques/aviation-civile</a></p>`,
  "Germany": `<h2>Germany</h2><p><a href="https://www.lba.de/EN/Home/home_node.html" target="_blank">https://www.lba.de/EN/Home/home_node.html</a></p>`,
  "Greece": `<h2>Greece</h2><p><a href="http://www.ypa.gr/en" target="_blank">http://www.ypa.gr/en</a></p>`,
  "Hungary": `<h2>Hungary</h2><p><a href="https://www.kozlekedesihatosag.kormany.hu/hu/web/legugyi-szakterulet" target="_blank">https://www.kozlekedesihatosag.kormany.hu/hu/web/legugyi-szakterulet</a></p>`,
  "Iceland": `<h2>Iceland</h2><p><a href="https://island.is/en/new-drone-rules" target="_blank">https://island.is/en/new-drone-rules</a></p>`,
  "Ireland": `<h2>Ireland</h2><p><a href="https://www.iaa.ie/general-aviation/drones" target="_blank">https://www.iaa.ie/general-aviation/drones</a></p>`,
  "Italy": `<h2>Italy</h2><p><a href="http://www.enac.gov.it/en" target="_blank">http://www.enac.gov.it/en</a></p>`,
  "Latvia": `<h2>Latvia</h2><p><a href="https://www.transport.lv/en/aviacija" target="_blank">https://www.transport.lv/en/aviacija</a></p>`,
  "Liechtenstein": `<h2>Liechtenstein</h2><p><a href="http://www.llv.li" target="_blank">http://www.llv.li</a></p>`,
  "Lithuania": `<h2>Lithuania</h2><p><a href="http://www.tka.lt/oro-transportas" target="_blank">http://www.tka.lt/oro-transportas</a></p>`,
  "Luxembourg": `<h2>Luxembourg</h2><p><a href="https://www.dac.gouvernement.lu" target="_blank">https://www.dac.gouvernement.lu</a></p>`,
  "Malta": `<h2>Malta</h2><p><a href="https://www.transport.gov.mt/aviation-502" target="_blank">https://www.transport.gov.mt/aviation-502</a></p>`,
  "Netherlands": `<h2>Netherlands</h2><p><a href="https://www.ilent.nl" target="_blank">https://www.ilent.nl</a></p>`,
  "Norway": `<h2>Norway</h2><p><a href="https://www.luftfartstilsynet.no/en" target="_blank">https://www.luftfartstilsynet.no/en</a></p>`,
  "Poland": `<h2>Poland</h2><p><a href="https://www.ulc.gov.pl" target="_blank">https://www.ulc.gov.pl</a></p>`,
  "Portugal": `<h2>Portugal</h2><p><a href="https://www.anac.pt" target="_blank">https://www.anac.pt</a></p>`,
  "Romania": `<h2>Romania</h2><p><a href="http://www.caa.ro" target="_blank">http://www.caa.ro</a></p>`,
  "Slovakia": `<h2>Slovakia</h2><p><a href="http://www.nsat.sk" target="_blank">http://www.nsat.sk</a></p>`,
  "Slovenia": `<h2>Slovenia</h2><p><a href="http://www.caa.si" target="_blank">http://www.caa.si</a></p>`,
  "Spain": `<h2>Spain</h2><p><a href="https://www.mitma.es/aereo" target="_blank">https://www.mitma.es/aereo</a></p>`,
  "Sweden": `<h2>Sweden</h2><p><a href="https://www.transportstyrelsen.se/en/aviation" target="_blank">https://www.transportstyrelsen.se/en/aviation</a></p>`,
  "Switzerland": `<h2>Switzerland</h2><p><a href="https://www.bazl.admin.ch" target="_blank">https://www.bazl.admin.ch</a></p>`,
  "Bahrain": `<h2>Bahrain</h2><p><a href="https://www.mtt.gov.bh/directorates/civil-aviation" target="_blank">https://www.mtt.gov.bh/directorates/civil-aviation</a></p>`,
  "Bangladesh": `<h2>Bangladesh</h2><p><a href="https://www.caab.gov.bd" target="_blank">https://www.caab.gov.bd</a></p>`,
  "Bhutan": `<h2>Bhutan</h2><p><a href="https://www.bcaa.gov.bt" target="_blank">https://www.bcaa.gov.bt</a></p>`,
  "Brunei": `<h2>Brunei</h2><p><a href="https://www.dca.gov.bn" target="_blank">https://www.dca.gov.bn</a></p>`,
  "Cambodia": `<h2>Cambodia</h2><p><a href="https://www.civilaviation.gov.kh/en/" target="_blank">https://www.civilaviation.gov.kh/en/</a></p>`,
  "China": `<h2>China</h2><p><a href="https://www.caac.gov.cn" target="_blank">https://www.caac.gov.cn</a></p>`,
  "Hong Kong (SAR)": `<h2>Hong Kong (SAR)</h2><p><a href="https://www.cad.gov.hk" target="_blank">https://www.cad.gov.hk</a></p>`,
  "India": `<h2>India</h2><p><a href="https://www.dgca.gov.in/digigov-portal/baseLocale=en_US?page=jsp/dgca/InventoryList/headerblock/drones/RPAS.html" target="_blank">https://www.dgca.gov.in/digigov-portal/baseLocale=en_US?page=jsp/dgca/InventoryList/headerblock/drones/RPAS.html</a></p>`,
  "Indonesia": `<h2>Indonesia</h2><p><a href="https://hubud.dephub.go.id" target="_blank">https://hubud.dephub.go.id</a></p>`,
  "Iran": `<h2>Iran</h2><p><a href="https://www.cao.ir" target="_blank">https://www.cao.ir</a></p>`,
  "Iraq": `<h2>Iraq</h2><p><a href="https://www.icaa.gov.iq" target="_blank">https://www.icaa.gov.iq</a></p>`,
  "Israel": `<h2>Israel</h2><p><a href="https://www.caa.gov.il" target="_blank">https://www.caa.gov.il</a></p>`,
  "Japan": `<h2>Japan</h2><p><a href="https://www.mlit.go.jp/en/koku/index.html" target="_blank">https://www.mlit.go.jp/en/koku/index.html</a></p>`,
  "Jordan": `<h2>Jordan</h2><p><a href="https://carc.gov.jo/en" target="_blank">https://carc.gov.jo/en</a></p>`,
  "Kazakhstan": `<h2>Kazakhstan</h2><p><a href="https://caa.gov.kz/en" target="_blank">https://caa.gov.kz/en</a></p>`,
  "Kuwait": `<h2>Kuwait</h2><p><a href="https://www.dgca.gov.kw" target="_blank">https://www.dgca.gov.kw</a></p>`,
  "Kyrgyzstan": `<h2>Kyrgyzstan</h2><p><a href="https://www.caa.kg" target="_blank">https://www.caa.kg</a></p>`,
  "Laos": `<h2>Laos</h2><p><a href="https://www.dcal.gov.la" target="_blank">https://www.dcal.gov.la</a></p>`,
  "Algeria": `<h2>Algeria</h2><p><a href="http://www.dgac.dz" target="_blank">http://www.dgac.dz</a></p>`,
  "Angola": `<h2>Angola</h2><p><a href="http://www.inavic.gov.ao" target="_blank">http://www.inavic.gov.ao</a></p>`,
  "Benin": `<h2>Benin</h2><p><a href="http://www.anac.bj" target="_blank">http://www.anac.bj</a></p>`,
  "Botswana": `<h2>Botswana</h2><p><a href="http://www.caab.co.bw" target="_blank">http://www.caab.co.bw</a></p>`,
  "Burkina Faso": `<h2>Burkina Faso</h2><p><a href="http://www.asecna.org/bf" target="_blank">http://www.asecna.org/bf</a></p>`,
  "Burundi": `<h2>Burundi</h2><p><a href="http://www.anac.bi" target="_blank">http://www.anac.bi</a></p>`,
  "Cabo Verde": `<h2>Cabo Verde</h2><p><a href="http://www.iac.cv" target="_blank">http://www.iac.cv</a></p>`,
  "Cameroon": `<h2>Cameroon</h2><p><a href="http://www.anac.cm" target="_blank">http://www.anac.cm</a></p>`,
  "Central African Republic": `<h2>Central African Republic</h2><p><a href="http://www.anacafricas.com" target="_blank">http://www.anacafricas.com</a></p>`,
  "Chad": `<h2>Chad</h2><p><a href="http://www.anac-tchad.org" target="_blank">http://www.anac-tchad.org</a></p>`,
  "Comoros": `<h2>Comoros</h2><p><a href="http://www.anac-comores.km" target="_blank">http://www.anac-comores.km</a></p>`,
  "Côte d’Ivoire": `<h2>Côte d’Ivoire</h2><p><a href="http://www.anac.ci" target="_blank">http://www.anac.ci</a></p>`,
  "Democratic Republic of the Congo": `<h2>Democratic Republic of the Congo</h2><p><a href="http://www.aac.cd" target="_blank">http://www.aac.cd</a></p>`,
  "Djibouti": `<h2>Djibouti</h2><p><a href="http://www.anac.dj" target="_blank">http://www.anac.dj</a></p>`,
  "Egypt": `<h2>Egypt</h2><p><a href="http://www.civilaviation.gov.eg" target="_blank">http://www.civilaviation.gov.eg</a></p>`,
  "Equatorial Guinea": `<h2>Equatorial Guinea</h2><p><a href="http://www.aac.gq" target="_blank">http://www.aac.gq</a></p>`,
  "Eritrea": `<h2>Eritrea</h2><p><a href="http://www.caaer.org" target="_blank">http://www.caaer.org</a></p>`,
  "Eswatini": `<h2>Eswatini</h2><p><a href="http://www.eswacaa.org.sz" target="_blank">http://www.eswacaa.org.sz</a></p>`,
  "Ethiopia": `<h2>Ethiopia</h2><p><a href="http://www.ecaa.gov.et" target="_blank">http://www.ecaa.gov.et</a></p>`,
  "Gabon": `<h2>Gabon</h2><p><a href="http://www.anac.ga" target="_blank">http://www.anac.ga</a></p>`,
  "Gambia": `<h2>Gambia</h2><p><a href="http://www.gcaa.gm" target="_blank">http://www.gcaa.gm</a></p>`,
  "Ghana": `<h2>Ghana</h2><p><a href="http://www.gcaa.com.gh" target="_blank">http://www.gcaa.com.gh</a></p>`,
  "Guinea": `<h2>Guinea</h2><p><a href="http://www.anac-guinee.org" target="_blank">http://www.anac-guinee.org</a></p>`,
  "Guinea-Bissau": `<h2>Guinea-Bissau</h2><p><a href="http://www.anac.gov.gw" target="_blank">http://www.anac.gov.gw</a></p>`,
  "Kenya": `<h2>Kenya</h2><p><a href="http://www.kcaa.or.ke" target="_blank">http://www.kcaa.or.ke</a></p>`,
  "Lesotho": `<h2>Lesotho</h2><p><a href="http://www.lcaa.org.ls" target="_blank">http://www.lcaa.org.ls</a></p>`,
  "Liberia": `<h2>Liberia</h2><p><a href="http://www.lcaa.gov.lr" target="_blank">http://www.lcaa.gov.lr</a></p>`,
  "Libya": `<h2>Libya</h2><p><a href="http://www.lycaa.gov.ly" target="_blank">http://www.lycaa.gov.ly</a></p>`,
  "Madagascar": `<h2>Madagascar</h2><p><a href="http://www.oacm.mg" target="_blank">http://www.oacm.mg</a></p>`,
  "Malawi": `<h2>Malawi</h2><p><a href="http://www.caam.gov.mw" target="_blank">http://www.caam.gov.mw</a></p>`,
  "Mali": `<h2>Mali</h2><p><a href="http://www.anac-mali.org" target="_blank">http://www.anac-mali.org</a></p>`,
  "Mauritania": `<h2>Mauritania</h2><p><a href="http://www.anac.mr" target="_blank">http://www.anac.mr</a></p>`,
  "Mauritius": `<h2>Mauritius</h2><p><a href="http://www.caa.mu" target="_blank">http://www.caa.mu</a></p>`,
  "Morocco": `<h2>Morocco</h2><p><a href="http://www.onda.ma" target="_blank">http://www.onda.ma</a></p>`,
  "Mozambique": `<h2>Mozambique</h2><p><a href="http://www.aacm.co.mz" target="_blank">http://www.aacm.co.mz</a></p>`,
  "Namibia": `<h2>Namibia</h2><p><a href="http://www.ncaa.com.na" target="_blank">http://www.ncaa.com.na</a></p>`,
  "Niger": `<h2>Niger</h2><p><a href="http://www.anac-niger.org" target="_blank">http://www.anac-niger.org</a></p>`,
  "Nigeria": `<h2>Nigeria</h2><p><a href="http://www.ncaa.gov.ng" target="_blank">http://www.ncaa.gov.ng</a></p>`,
  "Rwanda": `<h2>Rwanda</h2><p><a href="http://www.caa.rw" target="_blank">http://www.caa.rw</a></p>`,
  "Senegal": `<h2>Senegal</h2><p><a href="http://www.anac-senegal.com" target="_blank">http://www.anac-senegal.com</a></p>`,
  "Seychelles": `<h2>Seychelles</h2><p><a href="http://www.scaa.sc" target="_blank">http://www.scaa.sc</a></p>`,
  "Sierra Leone": `<h2>Sierra Leone</h2><p><a href="http://www.slcaa.sl" target="_blank">http://www.slcaa.sl</a></p>`,
  "Somalia": `<h2>Somalia</h2><p><a href="http://www.scama.so" target="_blank">http://www.scama.so</a></p>`,
  "South Africa": `<h2>South Africa</h2><p><a href="https://www.caa.co.za/industry-information/uas/" target="_blank">https://www.caa.co.za/industry-information/uas/</a></p>`,
  "South Sudan": `<h2>South Sudan</h2><p><a href="http://www.ssaa.gov.ss" target="_blank">http://www.ssaa.gov.ss</a></p>`,
  "Sudan": `<h2>Sudan</h2><p><a href="http://www.sudancaa.gov.sd" target="_blank">http://www.sudancaa.gov.sd</a></p>`,
  "Tanzania": `<h2>Tanzania</h2><p><a href="http://www.tcaa.go.tz" target="_blank">http://www.tcaa.go.tz</a></p>`,
  "Togo": `<h2>Togo</h2><p><a href="http://www.anac.tg" target="_blank">http://www.anac.tg</a></p>`,
  "Tunisia": `<h2>Tunisia</h2><p><a href="http://www.dgac.nat.tn" target="_blank">http://www.dgac.nat.tn</a></p>`,
  "Uganda": `<h2>Uganda</h2><p><a href="http://www.caa.co.ug" target="_blank">http://www.caa.co.ug</a></p>`,
  "Zambia": `<h2>Zambia</h2><p><a href="http://www.caaz.co.zm" target="_blank">http://www.caaz.co.zm</a></p>`,
  "Zimbabwe": `<h2>Zimbabwe</h2><p><a href="http://www.caaz.co.zw" target="_blank">http://www.caaz.co.zw</a></p>`,
  "United States of America": `<h2>United States</h2><p><a href="https://www.faa.gov/uas" target="_blank">https://www.faa.gov/uas</a></p>`,
  "Canada": `<h2>Canada</h2><p><a href="https://tc.canada.ca/en/aviation/drone-safety" target="_blank">https://tc.canada.ca/en/aviation/drone-safety</a></p>`,
  "Mexico": `<h2>Mexico</h2><p><a href="https://www.gob.mx/afac/acciones-y-programas/rpas-drones" target="_blank">https://www.gob.mx/afac/acciones-y-programas/rpas-drones</a></p>`,
  "Belize": `<h2>Belize</h2><p><a href="https://civilaviation.gov.bz" target="_blank">https://civilaviation.gov.bz</a></p>`,
  "Costa Rica": `<h2>Costa Rica</h2><p><a href="https://www.dgac.go.cr" target="_blank">https://www.dgac.go.cr</a></p>`,
  "El Salvador": `<h2>El Salvador</h2><p><a href="https://www.aac.gob.sv" target="_blank">https://www.aac.gob.sv</a></p>`,
  "Guatemala": `<h2>Guatemala</h2><p><a href="https://www.dgac.gob.gt" target="_blank">https://www.dgac.gob.gt</a></p>`,
  "Honduras": `<h2>Honduras</h2><p><a href="https://ahac.gob.hn" target="_blank">https://ahac.gob.hn</a></p>`,
  "Nicaragua": `<h2>Nicaragua</h2><p><a href="https://www.inac.gob.ni" target="_blank">https://www.inac.gob.ni</a></p>`,
  "Panama": `<h2>Panama</h2><p><a href="https://www.aeronautica.gob.pa" target="_blank">https://www.aeronautica.gob.pa</a></p>`,
  "Argentina": `<h2>Argentina</h2><p><a href="https://www.argentina.gob.ar/anac" target="_blank">https://www.argentina.gob.ar/anac</a></p>`,
  "Brazil": `<h2>Brazil</h2><p><a href="https://www.gov.br/anac/en" target="_blank">https://www.gov.br/anac/en</a></p>`,
  "Chile": `<h2>Chile</h2><p><a href="https://www.dgac.gob.cl" target="_blank">https://www.dgac.gob.cl</a></p>`,
  "Colombia": `<h2>Colombia</h2><p><a href="https://www.aerocivil.gov.co" target="_blank">https://www.aerocivil.gov.co</a></p>`,
  "Peru": `<h2>Peru</h2><p><a href="https://portal.mtc.gob.pe/page_english/front-end/civilaviation/index.html" target="_blank">https://portal.mtc.gob.pe/page_english/front-end/civilaviation/index.html</a></p>`,
  "Ecuador": `<h2>Ecuador</h2><p><a href="https://www.aviacioncivil.gob.ec" target="_blank">https://www.aviacioncivil.gob.ec</a></p>`,
  "Bolivia": `<h2>Bolivia</h2><p><a href="https://www.dgac.gob.bo" target="_blank">https://www.dgac.gob.bo</a></p>`,
  "Paraguay": `<h2>Paraguay</h2><p><a href="https://www.dinac.gov.py/v3" target="_blank">https://www.dinac.gov.py/v3</a></p>`,
  "Uruguay": `<h2>Uruguay</h2><p><a href="https://dinacia.gub.uy" target="_blank">https://dinacia.gub.uy</a></p>`,
  "Venezuela": `<h2>Venezuela</h2><p><a href="http://www.inac.gob.ve" target="_blank">http://www.inac.gob.ve</a></p>`,
  "Guyana": `<h2>Guyana</h2><p><a href="https://www.gcaa-gy.org/" target="_blank">https://www.gcaa-gy.org/</a></p>`,
  "Bahamas": `<h2>Bahamas</h2><p><a href="https://caabahamas.com" target="_blank">https://caabahamas.com</a></p>`,
  "Barbados": `<h2>Barbados</h2><p><a href="http://www.bcad.gov.bb" target="_blank">http://www.bcad.gov.bb</a></p>`,
  "Cuba": `<h2>Cuba</h2><p><a href="https://www.iacc.gob.cu/" target="_blank">https://www.iacc.gob.cu/</a></p>`,
  "Dominican Republic": `<h2>Dominican Republic</h2><p><a href="https://www.idac.gob.do/" target="_blank">https://www.idac.gob.do/</a></p>`,
  "Haiti": `<h2>Haiti</h2><p><a href="https://aan.gouv.ht" target="_blank">https://aan.gouv.ht</a></p>`,
  "Jamaica": `<h2>Jamaica</h2><p><a href="https://jcaa.aero/" target="_blank">https://jcaa.aero/</a></p>`,
  "Trinidad and Tobago": `<h2>Trinidad and Tobago</h2><p><a href="https://www.caa.gov.tt/" target="_blank">https://www.caa.gov.tt/</a></p>`,
  "Eastern Caribbean": `<h2>Eastern Caribbean</h2><p><a href="https://eccaa.aero" target="_blank">https://eccaa.aero</a></p>`,
  "Australia": `<h2>Australia</h2><p><a href="https://www.casa.gov.au/drones" target="_blank">https://www.casa.gov.au/drones</a></p>`,
  "New Zealand": `<h2>New Zealand</h2><p><a href="https://www.aviation.govt.nz/drones/" target="_blank">https://www.aviation.govt.nz/drones/</a></p>`,
  "Papua New Guinea": `<h2>Papua New Guinea</h2><p><a href="https://casapng.gov.pg" target="_blank">https://casapng.gov.pg</a></p>`,
  "Fiji": `<h2>Fiji</h2><p><a href="https://www.caaf.org.fj" target="_blank">https://www.caaf.org.fj</a></p>`,
  "Pacific States": `<h2>Pacific States</h2><p><a href="https://paso.aero" target="_blank">https://paso.aero</a></p>`,
};